config/routes.rb
Rails.application.routes.draw do
  mount API => '/'
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  get 'login' => 'user_sessions#new', :as => :login

	post 'logout' => 'user_sessions#destroy', :as => :logout
	resources :user_sessions
	root 'user_sessions#new'

	resources :tickets

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  has_many :variants, through: :order_items

  accepts_nested_attributes_for :order_items

  validates :email, :name, :card_token, presence: true
  


  def amount
    order_items.inject(0) { |sum, item| sum + item.count * item.variant.price }
  end


  def payment_proccess
    customer = Stripe::Customer.create email: email, 
                                       card: card_token

    Stripe::Charge.create customer: customer.id,
                          amount: amount.to_i * 100,
                          description: name,
                          currency: 'rub'
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :variant
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :variants, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  after_create :send_notification

  private

  def send_notification
    result = TicketMailer.recieve_message(self).deliver_now
    puts "MAILGUN_DOMAIN => #{result}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

	validates :password, length: { minimum: 3  }, if: -> { new_record? || changes["password"]  }
	validates :password, confirmation: true, if: -> { new_record? || changes["password"]  }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"]  }
	validates :email, uniqueness: true
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
	  before_action :require_login

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    def not_authenticated
      redirect_to root_path, alert: "Нужно войти."
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/order_items_controller.rb
module Admin
  class OrderItemsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = OrderItem.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   OrderItem.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/tickets_controller.rb
module Admin
  class TicketsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Ticket.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Ticket.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/variants_controller.rb
module Admin
  class VariantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Variant.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Variant.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exceptioe
	before_action :require_login
			
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	skip_before_action :require_login, only: [:create, :new, :show]

	def create
		@ticket = Ticket.new ticket_params
		if @ticket.save
			redirect_to @ticket, notice: "Сообщение принято"
		else
			redirect_to 'new'
		end
	end

	

	private

	def ticket_params
		params.permit(:name, :email, :message)
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]

  def new
		@user = User.new
  end

  def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to(:admin_root, notice: 'Login successful')
		else
			flash.now[:alert] = 'Login failed'
      render action: 'new'
		end
  end

  def destroy
		logout
		redirect_to(:root, notice: "Logged out!")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/variants/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label cell-label--<%= attr_type.html_class %>
          cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
            <%= attr_name.to_s.titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/variants/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/variants/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "Edit #{page.page_title}" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "Show #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<%= render "form", page: page %>

app/views/admin/variants/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="Search"
      value="<%= search_term %>"
      aria-label="Search"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/admin/variants/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "New #{page.resource_name.titleize}" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to 'Back', :back, class: "button" %>
  </div>
</header>

<%= render 'form', page: page %>

app/views/admin/variants/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.page_title } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "Edit",
      [:edit, namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<dl>
  <% page.attributes.each do |attribute| %>
    <dt class="attribute-label"><%= attribute.name.titleize %></dt>

    <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
        ><%= render_field attribute %></dd>
  <% end %>
</dl>

app/views/fields/variant_image_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/variant_image_field/_index.html.erb
<%= image_tag field.to_s %>

app/views/fields/variant_image_field/_show.html.erb
<%= image_tag field.to_s %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelgaMessage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700'
	  rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main" role="main">

  <% flash.each do |key, value| %>
    <p class="flash"> <%= value %></p>
  <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/tickets/new.html.erb
<div class="go-back">
	<h1>Спасибо!</h1>
	<h2>Мы получили ваше сообщение</h2>
	<button onclick="history.back()">Вернуться назад</button>
</div>

app/views/tickets/show.html.erb
<div class="go-back">
	<h1>спасибо!</h1>
	<h2>мы получили ваше сообщение</h2>
	<button onclick="history.back()">вернуться назад</button>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
	  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>